Vagrant.configure("2") do |config|

  hostname = File.basename(Dir.getwd)
  config.vm.define "#{hostname}" do |app|
    app.vm.provider "virtualbox" do |vb|
      vb.gui = false
      vb.memory = "4096"
      vb.cpus = 4
    end
    app.vm.hostname = "#{hostname}"
    app.vm.box = "bento/centos-7.3"
    app.vm.box_check_update = false
    app.ssh.insert_key = false
    app.ssh.private_key_path = ['~/.vagrant.d/insecure_private_key']
    app.vm.network "private_network", ip: "10.0.111.111"
    app.vm.provision "file", source: "~/.vagrant.d/insecure_private_key", destination: "/home/vagrant/.ssh/id_rsa"
    app.vm.provision "file", source: "../config/etc_ansible_hosts", destination: "/home/vagrant/etc_ansible_hosts"
    app.vm.provision "file", source: "../config/playbook_utils.yml", destination: "/home/vagrant/playbook_utils.yml"
  end
end
